import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import Navbar from "@/components/layouts/Navbar";
import { routing } from "@/i18n/routing";
import "@/styles/globals.css";
import { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <div className="relative">
            <div className="relative z-10">
              <div className="flex flex-col justify-between min-h-[1500px]">
                <Header />
                <Navbar className="absolute w-full max-w-3xl left-1/2 transform -translate-x-1/2 top-12" />
                {children}
                <Footer />
              </div>
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
